general.ipc_socket = true

[colors.bright]
black = "0x4f4f4f"
blue = "0x5c6bc0"
cyan = "0x18ffff"
green = "0x9ccc65"
magenta = "0xe040fb"
red = "0xff1744"
white = "0xdddddd"
yellow = "0xffeb3b"

[colors.normal]
black = "0x1e1e1e"
blue = "0x42a5f5"
cyan = "0x00acc1"
green = "0x8bc34a"
magenta = "0xd81b60"
red = "0xef5350"
white = "0xcccccc"
yellow = "0xffb900"

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[cursor.style]
blinking = "Never"

[font]
builtin_box_drawing = true
size = 10.0

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9
